#!/bin/bash

art="/tmp/albumart.png"
oldsong=" "

while true; do
    # wait until new mpd player(start/stop/seek) event
    mpc idle player > /dev/null

    song=$(mpc current)

    if [ "$oldsong" != "$song" ]; then
        oldsong=$song
        file="$(mpc current -f "%file%")"

        if [ -e $art ]; then
            rm $art
        fi
        ffmpeg -v quiet -y -i "/home/sam/music/${file}" -s 50x50 $art > /dev/null

        notify-send -i "$art" "Now Playing" "$song"
    fi
done
