#! /bin/sh

# bspwm hotkeys
sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a caca\ for\ X state=floating folow=on

# set wallpaper
~/.fehbg &
# hide mouse cursor
unclutter -root &
#start mpd
mpd &


# Colors
bspc config active_border_color "{{ b_black }}"
bspc config focused_border_color "{{ n_primary }}"
bspc config normal_border_color "{{ n_black }}"
bpsc config presel_feedback_color "{{ n_secondary }}"
